name: "Tests"

on: ["push", "pull_request"]

jobs:
  test:
    name: "Run"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go-version: ["1.20", "stable"]
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "actions/setup-go@v4"
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: "Get dependencies"
        run: go get ./...
      - name: "Generate more test cases from specification"
        run: go generate ./...
      - name: "Run unit tests"
        run: go test -v -cover ./...
